/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Receptionist;

import ui.Patient.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.AmbulanceOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Patients.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kohli
 */
public class ReceptionistDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientDashboardJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Patient patient;
    private EcoSystem business;
    
    
                                                                                                                                                        
    public ReceptionistDashboardJPanel(JPanel userProcessContainer,UserAccount account,  Organization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnUserHistory = new javax.swing.JButton();
        btnPersonalInfo = new javax.swing.JButton();
        btnPersonalInfo1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 153, 102));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("Receptionist Work Panel");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Navigate to:");

        btnUserHistory.setBackground(new java.awt.Color(255, 153, 102));
        btnUserHistory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUserHistory.setText("User History");
        btnUserHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserHistoryActionPerformed(evt);
            }
        });

        btnPersonalInfo.setBackground(new java.awt.Color(255, 153, 102));
        btnPersonalInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPersonalInfo.setText("Personal Information");
        btnPersonalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoActionPerformed(evt);
            }
        });

        btnPersonalInfo1.setBackground(new java.awt.Color(255, 153, 102));
        btnPersonalInfo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPersonalInfo1.setText("Request patient transfer");
        btnPersonalInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(btnPersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUserHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPersonalInfo1))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnPersonalInfo)
                .addGap(18, 18, 18)
                .addComponent(btnPersonalInfo1)
                .addGap(24, 24, 24)
                .addComponent(btnUserHistory)
                .addContainerGap(104, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserHistoryActionPerformed
        // TODO add your handling code here:
        
        UserHistoryJPanel userHistoryJPanel=new UserHistoryJPanel(userProcessContainer, this.patient, this.userAccount,this.organization, this.enterprise,this.business);
        userProcessContainer.add("PatientHistoryJPanel", userHistoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
        
        
    }//GEN-LAST:event_btnUserHistoryActionPerformed

    private void btnPersonalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoActionPerformed
        // TODO add your handling code here:
        PatientPersonalInformationJPanel patientpersonalInformationJPanel=new PatientPersonalInformationJPanel(userProcessContainer, this.patient, this.userAccount,true);
        userProcessContainer.add("PatientPersonalInformationJPanel",patientpersonalInformationJPanel );
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPersonalInfoActionPerformed

    private void btnPersonalInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfo1ActionPerformed
        // TODO add your handling code hreere:
        RequestAmbulanceJPanel patientpersonalInformationJPanel=new RequestAmbulanceJPanel( userProcessContainer,  userAccount,  organization,  enterprise,  business);
        userProcessContainer.add("PatientPersonalInformationJPanel",patientpersonalInformationJPanel );
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPersonalInfo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPersonalInfo;
    private javax.swing.JButton btnPersonalInfo1;
    private javax.swing.JButton btnUserHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
