/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Lab;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.Lab;
import Business.Patients.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kohli
 */
public class LabDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabDashboardJPanel
     */
    JPanel CardLayoutJPanel;
    Organization organization;
    UserAccount account;
    Enterprise enterprise;
    //Lab lab;
    public LabDashboardJPanel(JPanel CardLayoutJPanel, UserAccount account,Organization organization,Enterprise enterprise) {
        initComponents();
        this.CardLayoutJPanel=CardLayoutJPanel;
        this.account=account;
        this.organization=organization;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRequestedTest = new javax.swing.JButton();
        btnLabInfo = new javax.swing.JButton();
        btnManageTest = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Navigate to:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Welcome to Lab Work Area");

        btnRequestedTest.setText("Requested Test");
        btnRequestedTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestedTestActionPerformed(evt);
            }
        });

        btnLabInfo.setText("Lab Information");
        btnLabInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabInfoActionPerformed(evt);
            }
        });

        btnManageTest.setText("Manage Test");
        btnManageTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnLabInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRequestedTest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnManageTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnRequestedTest)
                .addGap(48, 48, 48)
                .addComponent(btnLabInfo)
                .addGap(42, 42, 42)
                .addComponent(btnManageTest)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestedTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestedTestActionPerformed
        // TODO add your handling code here:
        RequestedTestJPanel requestedTestJPanel=new RequestedTestJPanel(CardLayoutJPanel,account);
        CardLayoutJPanel.add("RequestedTestJPanel",requestedTestJPanel);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel);
    }//GEN-LAST:event_btnRequestedTestActionPerformed

    private void btnLabInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabInfoActionPerformed
        // TODO add your handling code here:
        LabInfoJPanel labInfoJPanel=new LabInfoJPanel(CardLayoutJPanel,account);
        CardLayoutJPanel.add("LabInfoJPanel",labInfoJPanel);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel);
    }//GEN-LAST:event_btnLabInfoActionPerformed

    private void btnManageTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTestActionPerformed
        // TODO add your handling code here:
        ManageTestJPanel manageTestJPanel=new ManageTestJPanel(CardLayoutJPanel,account);
        CardLayoutJPanel.add("ManageTestJPanel",manageTestJPanel);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel);
    }//GEN-LAST:event_btnManageTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLabInfo;
    private javax.swing.JButton btnManageTest;
    private javax.swing.JButton btnRequestedTest;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
