/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Patient;

import ui.Receptionist.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.PharmacyOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacyOrganization;
import Business.Patients.Patient;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientTransferRequest;
import Business.WorkQueue.PharmacyRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
//import java.time.LocalDateTime;
//import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kohli
 */
public class RequestPharmacy extends javax.swing.JPanel {

    /**
     * Creates new form RequestPharmacyJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Patient patient;
    private boolean isPatientLoggedIn;
    private Enterprise ent;
    private EcoSystem business;
    private Organization organization;
    private Patient selectPatient;
    private WorkRequest wq;
    
    public RequestPharmacy(JPanel userProcessContainer, UserAccount account, Organization ambulanceDriverOrganization, Enterprise enterprise, EcoSystem business,WorkRequest wq) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.account = account;
        this.ent = enterprise;
        this.business=business;
        this.organization = ambulanceDriverOrganization;
        populatePharmacys();
        populateHospitals();
        //populateWorkRequests();
        this.wq = wq;
    }
    
    public void populateHospitals(){
              
    }

    public void populatePharmacys(){
        comboPharmacy.removeAllItems();
        
        String networkName = account.getEmployee().getAddress();
        
        for(Enterprise ent:business.getNetwork(networkName).getEnterpriseDirectory().getEnterpriseList()){
            if(!ent.getEnterpriseType().toString().contains("Pharmacy")){
                continue;
            }
            for(Organization org: ent.getOrganizationDirectory().getOrganizations(Organization.Type.Pharmacy)){
                comboPharmacy.addItem(org);
            }
        }      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblAmbulance = new javax.swing.JLabel();
        btnRequest = new javax.swing.JButton();
        comboPharmacy = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPharmacy = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("Request medicine");

        lblAmbulance.setText("Pharmacy");

        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        comboPharmacy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblPharmacy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pharmacy", "Prescription", "Staus"
            }
        ));
        jScrollPane1.setViewportView(tblPharmacy);
        if (tblPharmacy.getColumnModel().getColumnCount() > 0) {
            tblPharmacy.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(286, 286, 286))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAmbulance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(277, 277, 277))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRequest)
                        .addGap(338, 338, 338))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(320, 320, 320))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmbulance))
                .addGap(18, 18, 18)
                .addComponent(btnRequest)
                .addGap(103, 103, 103))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        
        PharmacyRequest patTransfer = new PharmacyRequest();
        patTransfer.setSender(account);
        
        //Get the ambulance driver user account
        PharmacyOrganization ambOrg = (PharmacyOrganization)comboPharmacy.getSelectedItem();
        UserAccount pharm = ambOrg.getUserAccountDirectory().getUserByRole(Role.RoleType.Pharmacist);
        patTransfer.setReceiver(pharm);
        patTransfer.setSender(account);
       
        //patTransfer.setPatient(selectPatient);
        patTransfer.setMessage((wq).getMessage());
        
        //Set time
//        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
//        LocalDateTime now = LocalDateTime.now();  
        //patTransfer.setTime(dtf.format(now));
        
        //Add to works queues
        pharm.getWorkQueue().getWorkRequestList().add(patTransfer);
        account.getWorkQueue().getWorkRequestList().add(patTransfer);
        
        patTransfer.setStatus("Requested Pharmacy");
        JOptionPane.showMessageDialog(this, "Pharmacy request raised");
        populateWorkRequests();
        
    }//GEN-LAST:event_btnRequestActionPerformed

    public void populateWorkRequests(){
        DefaultTableModel model = (DefaultTableModel) tblPharmacy.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest wq : account.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[3];
            if(wq.getStatus().equals("Requested Pharmacy")){
            row[0] = (PharmacyOrganization)comboPharmacy.getSelectedItem();
            row[1] = wq.getMessage();
            row[2] = wq.getStatus();
            }
            
            model.addRow(row);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequest;
    private javax.swing.JComboBox comboPharmacy;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmbulance;
    private javax.swing.JTable tblPharmacy;
    // End of variables declaration//GEN-END:variables

  
}
