/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DoctorRole;

import Business.Doctor.Doctor;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
//import ui.PatientRole.*;
import Business.Patients.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author foram
 */
 
public class DoctorPersonalInformationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientPersonalInformationJPanel
     */
    private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount account;
    private Doctor selectedDoctor;
    
    public DoctorPersonalInformationJPanel(JPanel userProcessContainer, UserAccount account, Organization org, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.organization=(DoctorOrganization)org;
        this.enterprise=enterprise;
        this.account=account;
        
        Employee emp = (Employee)account.getEmployee();
        selectedDoctor = organization.getDoctorDirectory().searchDoctorByEmployee(emp);

       //this.txtAddress.setEnabled(false);
       this.txtLicense.setEnabled(false);
       this.txtContactDetails.setEnabled(false);
       this.txtEmailID.setEnabled(false);
       this.txtDoctorName.setEnabled(false);
       this.jComboboxBloodGroup.setEnabled(false);
       this.jRadioBtnFemale.setEnabled(false);
       this.jRadioBtnMale.setEnabled(false);
      this.jRadioBtnFemale.setEnabled(false);
      this.btnUpdate.setEnabled(true);
       
       this.btnSave.setEnabled(false);
       
       populateDetails();
    }
    
    public void populateDetails(){
        txtDoctorID.setText(selectedDoctor.getDoctorId()+"");
        txtDoctorName.setText(selectedDoctor.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblPatientInfo = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblContactDetails = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblBloodGroup = new javax.swing.JLabel();
        txtDoctorID = new javax.swing.JTextField();
        txtDoctorName = new javax.swing.JTextField();
        txtLicense = new javax.swing.JTextField();
        txtContactDetails = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jComboboxBloodGroup = new javax.swing.JComboBox<>();
        jRadioBtnMale = new javax.swing.JRadioButton();
        jRadioBtnFemale = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboDepartment = new javax.swing.JComboBox();
        lblLicense = new javax.swing.JLabel();
        txtAge1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPatientInfo.setBackground(new java.awt.Color(255, 153, 102));
        lblPatientInfo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblPatientInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientInfo.setText("Doctor Information");
        lblPatientInfo.setOpaque(true);
        add(lblPatientInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 40));

        lblPatientID.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblPatientID.setText("Doctor Id:");
        add(lblPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, -1));

        lblPatientName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblPatientName.setText("Doctor Name:");
        add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, 20));

        lblContactDetails.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblContactDetails.setText("Contact Details:");
        add(lblContactDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        lblEmailID.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblEmailID.setText("Email ID:");
        add(lblEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 90, -1));

        lblAddress.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblAddress.setText("Address:");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 90, -1));

        lblAge.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblAge.setText("Age:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, -1));

        lblGender.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblGender.setText("Gender:");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, -1));

        lblBloodGroup.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblBloodGroup.setText("Blood Group:");
        add(lblBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 90, -1));

        txtDoctorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorIDActionPerformed(evt);
            }
        });
        add(txtDoctorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 210, -1));
        add(txtDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 210, -1));
        add(txtLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 210, -1));

        txtContactDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactDetailsActionPerformed(evt);
            }
        });
        add(txtContactDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 206, -1));

        txtEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIDActionPerformed(evt);
            }
        });
        add(txtEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 206, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 206, -1));

        jComboboxBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-", " " }));
        add(jComboboxBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 206, -1));

        jRadioBtnMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioBtnMale);
        jRadioBtnMale.setText("Male");
        add(jRadioBtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jRadioBtnFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioBtnFemale);
        jRadioBtnFemale.setText("Female");
        add(jRadioBtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        btnSave.setBackground(new java.awt.Color(255, 153, 102));
        btnSave.setText("Save ");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 291, 310, 30));

        btnUpdate.setBackground(new java.awt.Color(255, 153, 102));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 102));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Department");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        jComboDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboDepartment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jComboDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 210, 20));

        lblLicense.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblLicense.setText("License No:");
        add(lblLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        add(txtAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDoctorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorIDActionPerformed

    private void txtContactDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactDetailsActionPerformed

    private void txtEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        this.txtAddress.setEnabled(true);
        this.txtLicense.setEnabled(true);
        this.txtContactDetails.setEnabled(true);
        this.txtEmailID.setEnabled(true);
        this.txtDoctorName.setEnabled(true);
        this.jComboboxBloodGroup.setEnabled(true);
        this.jRadioBtnFemale.setEnabled(true);
        this.jRadioBtnMale.setEnabled(true);
        this.jRadioBtnFemale.setEnabled(true);
        this.btnUpdate.setEnabled(false);
       
       this.btnSave.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
//      patient.setAddress(txtAddress.getText());
//       patient.setEmailId(txtEmailID.getText());
//       patient.setName(txtPatientName.getText());
//       patient.setPhoneNo(txtContactDetails.getText());
//      patient.setAge(txtAge.getText());
//      patient.setBloodGroup(jComboboxBloodGroup.getSelectedItem().toString());
//      patient.setGender(buttonGroup1.getSelection().toString());
        
         this.txtAddress.setEnabled(false);
        this.txtLicense.setEnabled(false);
        this.txtContactDetails.setEnabled(false);
        this.txtEmailID.setEnabled(false);
        this.txtDoctorName.setEnabled(false);
        this.jComboboxBloodGroup.setEnabled(false);
        this.jRadioBtnFemale.setEnabled(false);
        this.jRadioBtnMale.setEnabled(false);
        this.jRadioBtnFemale.setEnabled(false);
        this.btnUpdate.setEnabled(true);
        this.btnSave.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboDepartment;
    private javax.swing.JComboBox<String> jComboboxBloodGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioBtnFemale;
    private javax.swing.JRadioButton jRadioBtnMale;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblContactDetails;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPatientInfo;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge1;
    private javax.swing.JTextField txtContactDetails;
    private javax.swing.JTextField txtDoctorID;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtLicense;
    // End of variables declaration//GEN-END:variables
}
