/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DoctorRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorDepartmentOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DoctorRequest;
import Business.WorkQueue.LabRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kohli
 */
public class LabRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabRequestJPanel
     */
     private JPanel CardLayoutJPanel;
     private Organization organization;
     private Enterprise enterprise;
    private UserAccount account;
    private EcoSystem business;
    private WorkRequest wq;
    
    public LabRequestJPanel(JPanel CardLayoutJPanel, UserAccount account, Organization organization, Enterprise enterprise,EcoSystem business,WorkRequest wq) {
        initComponents();
        this.CardLayoutJPanel=CardLayoutJPanel;
        this.organization=organization;
        this.enterprise=enterprise;
        this.account=account;
        this.business=business;
        this.wq=wq;
        populateLabs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void populateLabs(){
        cmbLabs.removeAllItems();
        
        for(Enterprise ent:business.getNetwork("Boston").getEnterpriseDirectory().getEnterpriseList()){
            
            if(!ent.getEnterpriseType().toString().equals("Lab")){
                continue;
            }
            for(Organization org:ent.getOrganizationDirectory().getOrganizationList()){
                if(!org.getType().toString().contains("Lab")){
                    continue;
                }
                cmbLabs.addItem(org);
            }
            
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSelectLab = new javax.swing.JLabel();
        cmbLabs = new javax.swing.JComboBox();
        lblSelectTest = new javax.swing.JLabel();
        btnRequestTest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTest = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(255, 153, 102));
        lblTitle.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Lab Test Request");
        lblTitle.setOpaque(true);

        lblSelectLab.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSelectLab.setText("Select Lab:");

        cmbLabs.setBackground(new java.awt.Color(255, 153, 102));
        cmbLabs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbLabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLabsActionPerformed(evt);
            }
        });

        lblSelectTest.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSelectTest.setText("Description:");

        btnRequestTest.setBackground(new java.awt.Color(255, 153, 102));
        btnRequestTest.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnRequestTest.setText("Request Test");
        btnRequestTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestTestActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtTest.setBackground(new java.awt.Color(255, 153, 102));
        txtTest.setColumns(20);
        txtTest.setRows(5);
        jScrollPane1.setViewportView(txtTest);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\foram\\Downloads\\blood-test.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(btnRequestTest))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSelectTest)
                                    .addComponent(lblSelectLab))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(cmbLabs, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(btnBack))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectLab)
                    .addComponent(cmbLabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectTest, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnRequestTest)
                .addGap(0, 87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayoutJPanel.remove(this);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.previous(CardLayoutJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbLabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLabsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLabsActionPerformed

    private void btnRequestTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestTestActionPerformed
        // TODO add your handling code here:
        
        LabOrganization labOrg = (LabOrganization)cmbLabs.getSelectedItem();
        UserAccount labAss = labOrg.getUserAccountDirectory().getUserByRole(Role.RoleType.LabAssistant);
        
        LabRequest labReq = new LabRequest();
        labReq.setDoctorRequest((DoctorRequest)wq);
        labReq.setReceiver(labAss);
        labReq.setSender((wq).getSender());
        labReq.setMessage(txtTest.getText());
        labReq.setStatus("Assigned to lab");
        //.getWorkQueue().getWorkRequestList().add(labReq);
        (wq).getSender().getWorkQueue().getWorkRequestList().add(labReq);
        labAss.getWorkQueue().getWorkRequestList().add(labReq);
        JOptionPane.showMessageDialog(this, "Lab Request Sent");
    }//GEN-LAST:event_btnRequestTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestTest;
    private javax.swing.JComboBox cmbLabs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelectLab;
    private javax.swing.JLabel lblSelectTest;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtTest;
    // End of variables declaration//GEN-END:variables
}
