/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kohli
 */
public class PrescribeMedicinesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrescribeMedicinesJPanel
     */
    private JPanel CardLayoutJPanel;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount account;
    private EcoSystem business;
    private WorkRequest wq;
    
    
    public PrescribeMedicinesJPanel(JPanel CardLayoutJPanel, UserAccount account, Organization organization, Enterprise enterprise,EcoSystem business,WorkRequest wq) {
    initComponents();
    this.CardLayoutJPanel=CardLayoutJPanel;
    this.organization=organization;
    this.enterprise=enterprise;
    this.account=account;
    this.business=business;
    this.wq=wq;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPrescribeMedicine = new javax.swing.JLabel();
        scrollPrescribeMedicnes = new javax.swing.JScrollPane();
        txtMedicinesRequest = new javax.swing.JTextArea();
        btnSendRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(255, 153, 102));
        lblTitle.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Prescription");
        lblTitle.setOpaque(true);

        lblPrescribeMedicine.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblPrescribeMedicine.setText("Prescribe Medicines:");

        txtMedicinesRequest.setBackground(new java.awt.Color(255, 153, 102));
        txtMedicinesRequest.setColumns(20);
        txtMedicinesRequest.setRows(5);
        scrollPrescribeMedicnes.setViewportView(txtMedicinesRequest);

        btnSendRequest.setBackground(new java.awt.Color(255, 153, 102));
        btnSendRequest.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnSendRequest.setText("Send Request");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 153, 102));
        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrescribeMedicine)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPrescribeMedicnes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSendRequest)))
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnBack)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrescribeMedicine)
                    .addComponent(scrollPrescribeMedicnes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSendRequest)
                .addContainerGap(99, Short.MAX_VALUE))
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayoutJPanel.remove(this);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.previous(CardLayoutJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
        // TODO add your handling code here:
        wq.setReceiver(wq.getSender());
        wq.setSender(account);
        wq.setStatus("Prescription");
        wq.setMessage(txtMedicinesRequest.getText());
        (wq).getSender().getWorkQueue().getWorkRequestList().add(wq);
        JOptionPane.showMessageDialog(this, "Prescription Sent");
        txtMedicinesRequest.setText("");
    }//GEN-LAST:event_btnSendRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JLabel lblPrescribeMedicine;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrollPrescribeMedicnes;
    private javax.swing.JTextArea txtMedicinesRequest;
    // End of variables declaration//GEN-END:variables
}
